# Generated by Django 4.0.5 on 2022-06-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordbook',
            name='word',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
