# Generated by Django 4.0.5 on 2022-06-05 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0002_alter_wordbook_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordbook',
            name='anagram_key',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordbook',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
