# Generated by Django 4.0.5 on 2022-06-07 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0003_wordbook_anagram_key_wordbook_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anagram',
            fields=[
                ('anagram_key', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('word_list', models.TextField()),
                ('anagrams_count', models.PositiveIntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wordbook',
            name='id',
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='word',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wordbook',
            name='anagram_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anagram.anagram'),
        ),
    ]
