# Generated by Django 4.0.5 on 2022-06-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0004_anagram_remove_wordbook_id_alter_wordbook_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anagram',
            name='proper_nouns_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anagram',
            name='proper_nouns_list',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
