# Generated by Django 4.0.5 on 2022-06-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anagram', '0005_anagram_proper_nouns_count_anagram_proper_nouns_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagram',
            name='proper_nouns_count',
        ),
        migrations.RemoveField(
            model_name='anagram',
            name='proper_nouns_list',
        ),
    ]
